---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: miniflux-secret
    template:
      data:
        # App
        ADMIN_USERNAME: "{{ .MINIFLUX_ADMIN_USERNAME }}"
        ADMIN_PASSWORD: "{{ .MINIFLUX_ADMIN_PASSWORD }}"
        DATABASE_URL: "postgres://{{ .MINIFLUX_POSTGRES_USER }}:{{ .MINIFLUX_POSTGRES_PASS }}@192.168.106.30/miniflux?sslmode=disable"
        OAUTH2_CLIENT_ID: "{{ .MINIFLUX_OAUTH2_CLIENT_ID }}"
        OAUTH2_CLIENT_SECRET: "{{ .MINIFLUX_OAUTH2_CLIENT_SECRET }}"
        OAUTH2_OIDC_DISCOVERY_ENDPOINT: "{{ .MINIFLUX_OAUTH2_OIDC_DISCOVERY_ENDPOINT }}"
        OAUTH2_PROVIDER: "oidc"
        OAUTH2_REDIRECT_URL: "https://reader.tansanrao.net/oauth2/oidc/callback"
        OAUTH2_USER_CREATION: "1"
        # Postgres Init
        INIT_POSTGRES_DBNAME: miniflux
        INIT_POSTGRES_HOST: 192.168.106.30
        INIT_POSTGRES_USER: "{{ .MINIFLUX_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .MINIFLUX_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: miniflux
    - extract:
        key: postgres
