---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph
data:
  data: pve0=192.168.106.10:6789,pve0=192.168.106.11:6789,pve0=192.168.106.12:6789
  mapping: "{}"
  maxMonId: "2"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-cluster-user-command
  namespace: rook-ceph
data:
  args: ""
  command: ""
