---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.16.1
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    toolbox:
      enabled: true
      image: quay.io/ceph/ceph:v18.2.4
    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v18.2.4
      external:
        enable: true
      crashCollector:
        disable: false
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
      healthCheck:
        daemonHealth:
          mon:
            disabled: false
            interval: 45s
      network:
        provider: host
        connections:
          requireMsgr2: true

    cephBlockPools: {}
    cephFileSystems: {}
    cephObjectStores: {}
