---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./shared/ks.yaml
  - ./jellyfin/ks.yaml
  - ./pinchflat/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr-anime/ks.yaml
  - ./recyclarr/ks.yaml
  - ./jellyseerr/ks.yaml
