---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    vpn-routed-gateway: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    volsync.backube/privileged-movers: "true"
