---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1vv6hkfhwr0f36yxwmgytpae792qgp9lwfzrjy3cs8p4jesxtxess4pzvur"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1vv6hkfhwr0f36yxwmgytpae792qgp9lwfzrjy3cs8p4jesxtxess4pzvur"
