apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:XTjOU9bDHyhudpJPNQrBYPR8nCu0w9I4eqUeurI/GtLRmacNH1gi7w==,iv:CgcbPwKqKT8iMcxT5qdvLZZv5Gdwpb3svgkp1/A9xnY=,tag:ldobZBV60bSN1zUrEbFCpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vv6hkfhwr0f36yxwmgytpae792qgp9lwfzrjy3cs8p4jesxtxess4pzvur
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVi9qeHllRytVSzQ2VFB3
            T2R4RmZkeUF2cVBxR1J1aThOSkNSczVZMkQ4CjA1RmZMbm11TVB6QWorQS80aVc4
            KzJiLy9HVmI4YlJlb3JDN2JlMlpQUGMKLS0tIFNObnNFaU5sZ0dyUlc5M1BkaU1D
            SjhuRjVaWXY1emVXR2ovSW5iSzNISGsKYJTjHnr4KyctrXN4QmktojjoCWvJ8MlG
            xkiMAayv85R3B1eaWC6p6y9L+GH36PXyvQqs0rZmFFzFCTZX34rkHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-08T01:01:52Z"
    mac: ENC[AES256_GCM,data:eqwxxFPCfDjT8PjfDiBLcRnBEFmY4CV5LURp8/Lj015Gx1KUn9fh0MtA+zcNkJp402T3sUn4EI1+UUlf/vz4+LVoNpprgzfgFmYxq3cOcMI7GU/ddXdq3qZS3XWO1ZenQK1w6vZ64c/XVkKD14Dq35DlTC23SkgGySmbc70BQMA=,iv:wDOQ1+si8Lca7afPC7JmMMISjnASuMdZvGGJhljn90o=,tag:NZ6SniaUVTi08Ih8Us5blA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
