---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./asif-blog/ks.yaml
  - ./miniflux/ks.yaml
  - ./ocis/ks.yaml
  - ./shared/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./mealie/ks.yaml
  - ./actual/ks.yaml
  - ./authentik/ks.yaml
  - ./hoarder/ks.yaml
