---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &app hoarder-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *app
    template:
      data:
        # App
        encryption_key: "{{ .HOARDER_ENCRYPTION_KEY }}"
        meilisearch_master_key: "{{ .HOARDER_MEILISEARCH_MASTER_KEY }}"
        NEXTAUTH_URL: "https://hoarder.tansanrao.net"
        OAUTH_CLIENT_ID: "{{ .HOARDER_OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .HOARDER_OAUTH_CLIENT_SECRET }}"
        OAUTH_WELLKNOWN_URL: "{{ .HOARDER_OAUTH_WELLKNOWN_URL }}"
        OAUTH_PROVIDER_NAME: "Homelab SSO"
        DISABLE_PASSWORD_AUTH: "true"
        DISABLE_SIGNUPS: "true"
        OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"

  dataFrom:
    - extract:
        key: hoarder
