directives:
  child-src:
    - "'self'"
  connect-src:
    - "'self'"
  default-src:
    - "'none'"
  font-src:
    - "'self'"
  frame-ancestors:
    - "'self'"
  frame-src:
    - "'self'"
    - "https://embed.diagrams.net/"
    # In contrary to bash and docker the default is given after the | character
    - "https://${ONLYOFFICE_DOMAIN|onlyoffice.owncloud.test}/"
    - "https://${COLLABORA_DOMAIN|collabora.owncloud.test}/"
  img-src:
    - "'self'"
    - "data:"
    - "blob:"
    # In contrary to bash and docker the default is given after the | character
    - "https://${ONLYOFFICE_DOMAIN|onlyoffice.owncloud.test}/"
    - "https://${COLLABORA_DOMAIN|collabora.owncloud.test}/"
  manifest-src:
    - "'self'"
  media-src:
    - "'self'"
  object-src:
    - "'self'"
    - "blob:"
  script-src:
    - "'self'"
    - "'unsafe-inline'"
  style-src:
    - "'self'"
    - "'unsafe-inline'"
