---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      ocis:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-config:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.0.0
            command:
              - /bin/sh
              - -c
            args:
              - |
                if [ ! -f /etc/ocis/ocis.yaml ]; then ocis init; else exit 0; fi
            env:
              OCIS_INSECURE: true
            securityContext: &securityContext
              fsGroup: 65539
              fsGroupChangePolicy: OnRootMismatch
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL

        containers:
          ocis:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.0.0
            env:
              DEMO_USERS: false
              OCIS_LOG_COLOR: true
              OCIS_LOG_LEVEL: info
              OCIS_LOG_PRETTY: true
              OCIS_URL: https://files.tansanrao.net
              PROXY_TLS: false
              # Auto role assignment:
              # docs: https://doc.owncloud.com/ocis/next/deployment/services/s-list/proxy.html#automatic-role-assignments
              OCIS_OIDC_ISSUER: https://auth.tansanrao.net/
              PROXY_OIDC_ISSUER: https://auth.tansanrao.net/
              WEB_OIDC_ISSUER: https://auth.tansanrao.net/
              WEB_OIDC_METADATA_URL: https://auth.tansanrao.net/.well-known/openid-configuration
              PROXY_USER_OIDC_CLAIM: "preferred_username"
              PROXY_AUTOPROVISION_ACCOUNTS: true
              PROXY_AUTOPROVISION_CLAIM_USERNAME: "preferred_username"
              PROXY_AUTOPROVISION_CLAIM_EMAIL: "email"
              PROXY_AUTOPROVISION_CLAIM_DISPLAYNAME: "name"
              PROXY_ROLE_ASSIGNMENT_DRIVER: "oidc"
              PROXY_ROLE_ASSIGNMENT_CLAIM: "roles"
              PROXY_OIDC_REWRITE_WELLKNOWN: true
              PROXY_CSP_CONFIG_FILE_LOCATION: "/etc/ocis/csp.yaml"
              # Without this, I got the following errors in the ownCloud log:
              # Authentik: failed to verify access token: the JWT has an invalid kid: could not find kid in JWT header
              # Authelia: failed to verify access token: token contains an invalid number of segments
              # Auth0: failed to verify access token: token contains an invalid number of segments
              PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: "none"
              WEB_OIDC_SCOPE: "openid profile email groups"
            envFrom:
              - secretRef:
                  name: ocis-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 2Gi
            securityContext: &securityContext
              fsGroup: 65539
              fsGroupChangePolicy: OnRootMismatch
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: ocis
        ports:
          http:
            port: 9200

    ingress:
      app:
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: external.tansanrao.net
        hosts:
          - host: files.tansanrao.net
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        type: configMap
        name: ocis-configmap
        globalMounts:
          - path: /etc/ocis/web.yaml
            subPath: web.yaml
            readOnly: true
          - path: /etc/ocis/csp.yaml
            subPath: csp.yaml
            readOnly: true
      data:
        existingClaim: ocis-data
        globalMounts:
          - path: /var/lib/ocis
            subPath: data
          - path: /etc/ocis
            subPath: config
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
